// <auto-generated />
using System;
using Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20181226232751_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.0-rtm-35687")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Core.Channel", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("UserSecretLogin");

                    b.Property<string>("UserSecretLogin1");

                    b.HasKey("Id");

                    b.HasIndex("UserSecretLogin");

                    b.HasIndex("UserSecretLogin1");

                    b.ToTable("Channels");
                });

            modelBuilder.Entity("Core.RegularExpensesCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Category");

                    b.Property<string>("UserSecretLogin");

                    b.Property<string>("UserSecretLogin1");

                    b.HasKey("Id");

                    b.HasIndex("UserSecretLogin");

                    b.HasIndex("UserSecretLogin1");

                    b.ToTable("RegularExpensesCategories");
                });

            modelBuilder.Entity("Core.SingleExpense", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Amount");

                    b.Property<string>("Category");

                    b.Property<string>("ChannelId");

                    b.Property<DateTime>("CreationDateTime");

                    b.HasKey("Id");

                    b.HasIndex("ChannelId");

                    b.ToTable("SingleExpenses");
                });

            modelBuilder.Entity("Core.User", b =>
                {
                    b.Property<string>("SecretLogin")
                        .ValueGeneratedOnAdd();

                    b.HasKey("SecretLogin");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Core.Channel", b =>
                {
                    b.HasOne("Core.User", "User")
                        .WithMany()
                        .HasForeignKey("UserSecretLogin");

                    b.HasOne("Core.User")
                        .WithMany("Channels")
                        .HasForeignKey("UserSecretLogin1");
                });

            modelBuilder.Entity("Core.RegularExpensesCategory", b =>
                {
                    b.HasOne("Core.User", "User")
                        .WithMany()
                        .HasForeignKey("UserSecretLogin");

                    b.HasOne("Core.User")
                        .WithMany("RegularExpensesCategories")
                        .HasForeignKey("UserSecretLogin1");
                });

            modelBuilder.Entity("Core.SingleExpense", b =>
                {
                    b.HasOne("Core.Channel", "Channel")
                        .WithMany()
                        .HasForeignKey("ChannelId");
                });
#pragma warning restore 612, 618
        }
    }
}
